# helm pull prometheus-community/kube-prometheus-stack --version 66.3.1 --untar
# 이 파일은 upstream 원본. 절대 수동 편집 금지.
# 버전 변경 시: update-charts.sh monitoring 실행

apiVersion: v2
name: kube-prometheus-stack
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
type: application
version: 66.3.1
appVersion: v0.78.2
keywords:
  - operator
  - prometheus
  - kube-prometheus
home: https://github.com/prometheus-operator/kube-prometheus
sources:
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/kube-prometheus
maintainers:
  - email: andrew@quadcorps.co.uk
    name: andrewgkew
  - email: gianrubio@gmail.com
    name: gianrubio
  - email: github.gkarthiks@gmail.com
    name: gkarthiks
  - email: kube-prometheus-stack@sisti.pt
    name: GMartinez-Sisti
  - email: github@jkroepke.de
    name: jkroepke
  - email: scott@r6by.com
    name: scottrigby
  - email: miroslav.hadzhiev@gmail.com
    name: Xtigyro
  - email: quentin.bisson@gmail.com
    name: QuentinBisson
icon: https://raw.githubusercontent.com/prometheus/prometheus.io/main/static/prometheus_logo.svg
annotations:
  artifacthub.io/license: Apache-2.0
dependencies:
  - name: crds
    version: "0.0.0"
    condition: crds.enabled
  - name: kube-state-metrics
    version: "5.27.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "4.42.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: nodeExporter.enabled
  - name: grafana
    version: "8.8.*"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: prometheus-windows-exporter
    version: "0.7.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: windowsMonitoring.enabled
