{{- if .Values.cainjector.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cainjector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cert-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: cainjector
spec:
  replicas: {{ .Values.cainjector.replicaCount }}
  selector:
    matchLabels:
      {{- include "cainjector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cainjector.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cainjector.fullname" . }}
      securityContext:
        {{- toYaml .Values.cainjector.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-cainjector
          {{- if .Values.cainjector.image.digest }}
          image: "{{ .Values.cainjector.image.registry }}/{{ .Values.cainjector.image.repository }}@{{ .Values.cainjector.image.digest }}"
          {{- else }}
          image: "{{ .Values.cainjector.image.registry }}/{{ .Values.cainjector.image.repository }}:{{ default .Chart.AppVersion .Values.cainjector.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.cainjector.image.pullPolicy }}
          args:
            - --v=2
            - --leader-election-namespace={{ .Values.global.leaderElection.namespace }}
            {{- with .Values.cainjector.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.cainjector.securityContext | nindent 12 }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- with .Values.cainjector.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.cainjector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cainjector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cainjector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
